# Site settings
title: Casey Parnis  # From root config
email: caseyparnis@gmail.com  # From root config
description: >  # Description with line breaks ignored (from root config)

baseurl: ""  # From root config
url: "http://caseyparnis.com"  # From root config
github_username: caseyparnis  # From root config
timezone: America/Los_Angeles  # From root config
permalink: /:categories/:title/


#header_pages:
#  - about.md
 # - index.md
 # - categories.html

# Navigation Links
links:
  - [Home, /]  # Link to the homepage (from root config)
  - [About, /about/]  # Link to the about page (from root config)

# Special Links (Optional)
# Use this section for links withdifferent formatting (e.g., brackets)
# special_links:
# - [GitHub, https://github.com/caseyparnis]  # Link to your GitHub profile (replace with your username)

# Build settings
theme: minima  # From root config
plugins:
  - jekyll-feed  # From root config
  - jekyll-seo-tag  # From theme config (optional)

# Exclude from processing.
# ... (copy the exclude section from the root config)

# Theme-specific settings (optional)

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
#header_pages:
#  - about.md  # From theme config (optional)

# Set to `true` to show excerpts on the homepage.
show_excerpts: true  # From theme config (optional)

# Minima specific settings, which are only available from Minima 3.0 onward.
# ... (copy the minima section from the theme config - optional)
